name: Hello Workflow

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello from GitHub Actions!"

      - name: show the date and time
        run: date

      - name: show branch name
        run: echo "Branch {{github.ref_name}}

      - name: List repo files
        run: ls -la

      - name: Show operating system
        run: uname -a
