name: Task 2 - Pre-installed Tools

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tool Versions
        run: |
          echo "🐳 Docker Version:"
          docker --version

          echo "🐍 Python Version:"
          python3 --version

          echo "🟢 Node Version:"
          node --version

          echo "📦 Git Version:"
          git --version
